apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "space-21.fullname" . }}
  labels:
    {{- include "space-21.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "space-21.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "space-21.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # ДОБАВЛЯЕМ ПОДДЕРЖКУ ПЕРЕМЕННЫХ ОКРУЖЕНИЯ
          {{- if .Values.env }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}