apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ include "postgres.password" . | b64enc | quote }}
  postgres-user: {{ .Values.postgresql.username | b64enc | quote }}
  postgres-db: {{ .Values.postgresql.database | b64enc | quote }}
