{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "space-21.fullname" . }}-postgres-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "space-21.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.postgresql.database }}
  POSTGRES_USER: {{ .Values.postgresql.username }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "space-21.fullname" . }}-postgres-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "space-21.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storageSize }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "space-21.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "space-21.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "space-21.selectorLabels" . | nindent 6 }}
      component: postgres
  template:
    metadata:
      labels:
        {{- include "space-21.selectorLabels" . | nindent 8 }}
        component: postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: {{ include "space-21.fullname" . }}-postgres-config
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.postgresql.username }}
            - -d
            - {{ .Values.postgresql.database }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.postgresql.username }}
            - -d
            - {{ .Values.postgresql.database }}
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.postgresql.resources | nindent 10 }}
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: {{ include "space-21.fullname" . }}-postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "space-21.fullname" . }}-postgres-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "space-21.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "space-21.selectorLabels" . | nindent 4 }}
    component: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
{{- end }}
