apiVersion: v2
name: postgres
description: A Helm chart for PostgreSQL database
type: application
version: 0.1.0
appVersion: "15"
keywords:
  - database
  - postgresql
  - sql
maintainers:
  - name: Alexsey Popov
    email: garroshm@space-21.ru
sources:
  - https://github.com/s21platform
